###
GET http://localhost:1234/produto/listar

###
GET http://localhost:1234/buscar/codigo/6176d4fb626ad65453f77c30

###
POST http://localhost:1234/produto/cadastrar
content-type: application/json

{
    "nome": "COxinha",
    "codigo": "41",
    "categoria": "Alimentos",
    "preco": 29.90
}
###
POST http://localhost:1234/produto/alterar
content-type: application/json

{
    "nome": "Arroz",
    "codigo": "52",
    "categoria": "Comida",
    "preco": 29.90
}
###

GET http://localhost:1234/produto/remover/6176d4fb626ad65453f77c30
content-type: application/json


