###
GET http://localhost:1234/livro/listar
###
GET http://localhost:1234/buscar/isbn/12345678910

###
POST http://localhost:1234/livro/cadastrar
content-type: application/json

{
    "nome": "cOXINHA",
    "isbn": "444",
    "preco": 29.90
}
###
POST http://localhost:1234/livro/alterar
content-type: application/json

{
    "nome": "empadao",
    "isbn": "444",
    "preco": 1.50
}
###

GET http://localhost:1234/livro/remover/111


